{% set version = '1.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-harmony
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/harmony_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/harmony/harmony_{{ version }}.tar.gz
  sha256: a63c7d7cbbc5d183e8f919552e9d73044e0a89660856e80861a00eb5d25ac7b5

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'            # [win]
    - '*/Rblas.dll'        # [win]
    - '*/Rlapack.dll'      # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - libblas
    - liblapack
    - r-base
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress
    - r-rhpcblasctl
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-rlang
    - r-tibble
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - {{ native }}libwinpthread-git  # [win]
    - r-matrix
    - r-rcpp
    - r-rcpparmadillo
    - r-rcppprogress
    - r-rhpcblasctl
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-rlang
    - r-tibble

test:
  requires:
    - r-testthat
  source_files:
    - tests/
  commands:
    - $R -e "library('harmony')"                                                      # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"           # [not win]
    - "\"%R%\" -e \"library('harmony')\""                                             # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://portals.broadinstitute.org/harmony/
  dev_url: https://github.com/immunogenomics/harmony
  license: GPL-3.0-only
  summary: Implementation of the Harmony algorithm for single cell integration, described in
    Korsunsky et al <doi:10.1038/s41592-019-0619-0>. Package includes a standalone Harmony
    function and interfaces to external frameworks.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: harmony
# Title: Fast, Sensitive, and Accurate Integration of Single Cell Data
# Version: 1.2.0
# Authors@R: c( person("Ilya", "Korsunsky", email = "ilya.korsunsky@gmail.com", role = c("cre", "aut"), comment = c(ORCID = "0000-0003-4848-3948")), person("Martin Hemberg", email = "mhemberg@bwh.harvard.edu", role = c("aut"), comment = c(ORCID = "0000-0001-8895-5239")), person("Nikolaos Patikas", email = "nik.patik@gmail.com", role = c("aut", "ctb"), comment = c(ORCID = "0000-0002-3978-0134")), person("Hongcheng Yao", email = "hongchengyaonk@gmail.com", role = c("aut", "ctb"), comment = c(ORCID = "0000-0002-0743-4835")), person("Nghia", "Millard", email = "nmillard@g.harvard.edu", role = "aut", comment = c(ORCID = "0000-0002-0518-7674")), person("Jean", "Fan", email = "jeanfan@fas.harvard.edu", role = c("aut", "ctb"), comment = c(ORCID = "0000-0002-0212-5451")), person("Kamil", "Slowikowski", email = "kslowikowski@gmail.com", role = c("aut", "ctb"), comment = c(ORCID = "0000-0002-2843-6370")), person("Miles", "Smith", role = c("ctb")), person("Soumya", "Raychaudhuri", role = c("aut"), comment = c(ORCID = "0000-0002-1901-8265")) )
# Description: Implementation of the Harmony algorithm for single cell integration, described in Korsunsky et al <doi:10.1038/s41592-019-0619-0>. Package includes a standalone Harmony function and interfaces to external frameworks.
# URL: software.broadinstitute.org/harmony
# License: GPL-3
# Encoding: UTF-8
# RoxygenNote: 7.2.3
# Depends: R(>= 3.5.0), Rcpp
# LazyData: true
# LazyDataCompression: gzip
# LinkingTo: Rcpp, RcppArmadillo, RcppProgress
# Imports: dplyr, cowplot, ggplot2, Matrix, methods, tibble, rlang, RhpcBLASctl
# Suggests: SingleCellExperiment, Seurat (>= 4.1.1), testthat, knitr, rmarkdown, ggthemes, ggrepel, patchwork, tidyverse, tidyr, data.table
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2023-11-28 23:29:19 UTC; main
# Author: Ilya Korsunsky [cre, aut] (<https://orcid.org/0000-0003-4848-3948>), Martin Hemberg [aut] (<https://orcid.org/0000-0001-8895-5239>), Nikolaos Patikas [aut, ctb] (<https://orcid.org/0000-0002-3978-0134>), Hongcheng Yao [aut, ctb] (<https://orcid.org/0000-0002-0743-4835>), Nghia Millard [aut] (<https://orcid.org/0000-0002-0518-7674>), Jean Fan [aut, ctb] (<https://orcid.org/0000-0002-0212-5451>), Kamil Slowikowski [aut, ctb] (<https://orcid.org/0000-0002-2843-6370>), Miles Smith [ctb], Soumya Raychaudhuri [aut] (<https://orcid.org/0000-0002-1901-8265>)
# Maintainer: Ilya Korsunsky <ilya.korsunsky@gmail.com>
# Repository: CRAN
# Date/Publication: 2023-11-29 08:30:04 UTC
